In [47]:
import numpy as np

In [48]:
a = np.array([1,3,5])
b = np.array([6,5,10], dtype='int32')
a*b

array([ 6, 15, 50])

In [49]:
c = np.array([[9.0,8.0,10,0], [2.0,5.0,98.0,10.0]])
print(c)

[[ 9.  8. 10.  0.]
 [ 2.  5. 98. 10.]]


In [50]:
# Get number of dimensions
print(c.ndim)
# Get shape
print(c.shape) # (row, col)
# Get data type
print(b.dtype)
# Get size
print(b.itemsize)
# Get total size
print(b.nbytes)
print(c.nbytes)

2
(2, 4)
int32
4
12
64
